name: ZonePlugin
version: 1.0
main: ZoneSystem.ZonePlugin
api-version:
commands:
  zone:
    description: Verwalte Zonen
    usage: /<command> <create|reset> [Spielername#Zonennummer]
    permission: zone.use

permissions:
  zone.use:
    description: Erlaubt die Nutzung des Zone-Plugins
    default: true
  zone.reset.others:
    description: Erlaubt das Zurücksetzen von Zonen anderer Spieler
    default: op
depend: [WorldEdit]
