name: ZonePlugin
version: 1.0
main: ZoneSystem.ZonePlugin
api-version: 1.21.4
commands:
  zone:
    description: Manage zones
    usage: /<command> <create|confirm|reset|delete|info|permissions>
    permission: zone.use
  subzone:
    description: Verwalte Subzonen
    usage: /<command> create <Spielername>#<Zonennummer>
    permission: zone.use


permissions:
  zone.use:
    description: Erlaubt die Nutzung des Zone-Plugins
    default: true
  zone.reset.others:
    description: Erlaubt das Zurücksetzen von Zonen anderer Spieler
    default: op
depend: [WorldEdit]
