name: ZoneSystem
version: '1.0-SNAPSHOT'
main: ZoneSystem.ZonePlugin
api-version: '1.21'
description: A zone management system for Minecraft servers

commands:
  zone:
    description: Manage zones
    usage: /zone <create|confirm|reset|delete|info|permissions>
    permission: zone.use
    tab-completer: ZoneSystem.ZoneTabCompleter
  subzone:
    description: Manage subzones
    usage: /subzone <create|confirm|delete>
    permission: zone.subzone.use
    tab-completer: ZoneSystem.SubZoneTabCompleter

permissions:
  zone.use:
    description: Allows using the zone command
    default: true
  zone.subzone.use:
    description: Allows using the subzone command
    default: true
  zone.delete.own:
    description: Erlaubt das Löschen eigener Zonen
    default: op
  zone.delete.others:
    description: Erlaubt das Löschen fremder Zonen
    default: op
  zone.reset.own:
    description: Erlaubt das Zurücksetzen eigener Zonen
    default: op
  zone.reset.others:
    description: Erlaubt das Zurücksetzen fremder Zonen
    default: op
  subzone.delete.own:
    description: Erlaubt das Löschen eigener SubZonen
    default: true
  subzone.delete.others:
    description: Erlaubt das Löschen fremder SubZonen
    default: op


